name: wordle
description: Helper for solving Wordle puzzles
version: 1.0.0

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
